"""Build a self-contained results page from archived measurements and figures."""
import base64
import html
import json
from pathlib import Path

ROOT=Path(__file__).resolve().parent
def load(path): return json.loads((ROOT/path).read_text())
def image(path,alt):
    b64=base64.b64encode((ROOT/path).read_bytes()).decode()
    return f'<img loading="lazy" src="data:image/png;base64,{b64}" alt="{html.escape(alt)}">'
g=load('results/small-hot-molt-gates-21-22/comparison.json')
r=load('results/small-hot-reproduction/reproduction.json')
recon=load('results/reconstruction-layers17-25/reconstruction.json')
conditions={'baseline':'Original small','suppression_only':'Suppress small','addition_only':'Add hot','combined':'Suppress + add','natural_hot':'Natural hot'}
gate_rows=''.join(f'<tr><td>{name}</td>'+''.join(f'<td>{l["conditions"][c]["counts_by_token"][9]}</td>' for l in g['layers'])+f'<td>{g["readouts"][c]["top_token"]}</td><td>{100*g["readouts"][c]["P_cold"]:.4g}%</td></tr>' for c,name in conditions.items())
repro_rows=''.join(f'<tr><td>{x["strength"]}</td><td>{x["top_token"]}</td><td>{100*x["P_cold"]:.4g}%</td><td>{100*x["published_P_cold"]:.4g}%</td></tr>' for x in r['runs'])
recon_rows=''.join(f'<tr><td>{x["layer"]}</td><td>{x["all_tokens"]["standardized_mse"]:.6f}</td><td>{100*x["all_tokens"]["standardized_error_reduction"]:.2f}%</td><td>{x["all_tokens"]["mean_gate_l0"]:.3f}</td></tr>' for x in recon['results'])
explorer={'tokens':g['tokens'],'layers':[{'layer':l['layer'],'conditions':{c:l['conditions'][c]['active_by_token'] for c in conditions}} for l in g['layers']]}
status=load('archive-status.json') if (ROOT/'archive-status.json').exists() else {'status':'Backup preparation in progress'}
status_text=html.escape(status['status'])
page='''<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>Qwen3-4B · MOLT exploration</title><style>
:root{color-scheme:light;--ink:#172b42;--muted:#526377;--blue:#2357c6;--line:#dce4ed;--paper:#f5f7fa}*{box-sizing:border-box}body{margin:0;background:var(--paper);color:var(--ink);font:17px/1.65 system-ui,sans-serif}main{max-width:1120px;margin:auto;padding:40px 28px 80px}header{padding:36px 0 28px;border-bottom:1px solid var(--line)}.eyebrow{font-size:12px;letter-spacing:.16em;text-transform:uppercase;font-weight:750;color:var(--blue)}h1{font-size:clamp(34px,6vw,64px);letter-spacing:-.045em;line-height:1.08;margin:14px 0}h2{font-size:29px;line-height:1.25;letter-spacing:-.025em;margin:0 0 18px}h3{font-size:20px}.lead{max-width:850px;font-size:21px;color:var(--muted)}.meta{font-size:14px;color:var(--muted)}nav{display:flex;flex-wrap:wrap;gap:10px 22px;padding:18px 0}a{color:var(--blue);text-underline-offset:3px}.cards{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;margin:25px 0}.card,section{background:white;border:1px solid var(--line);border-radius:14px}.card{padding:22px}.big{font-size:34px;line-height:1.2;font-weight:750;color:var(--blue)}.card p{margin:7px 0 0;font-size:14px;color:var(--muted)}section{padding:30px;margin:24px 0;scroll-margin-top:20px}.number{font:700 13px system-ui;color:var(--blue);display:block;margin-bottom:12px}.note{background:#eef3fc;border-left:4px solid #4776d7;padding:16px 20px;margin:20px 0;border-radius:3px}.warning{background:#fff6e7;border-left-color:#c48a22}blockquote{margin:20px 0;padding:15px 20px;border-left:3px solid var(--blue);background:var(--paper);font-size:19px}table{width:100%;border-collapse:collapse;font-size:15px}th{text-align:left;color:var(--muted);font-size:12px;text-transform:uppercase;letter-spacing:.045em}td,th{padding:12px;border-bottom:1px solid var(--line)}tbody tr:last-child td{border-bottom:0}.scroll{overflow:auto}img{width:100%;height:auto;display:block;margin:20px 0;border:1px solid var(--line);border-radius:7px}code{font-size:.88em;background:#edf1f6;padding:2px 5px;border-radius:4px}details{margin:18px 0}summary{cursor:pointer;color:var(--blue);font-weight:650}.controls{display:flex;gap:15px;flex-wrap:wrap;margin:20px 0}label{display:flex;flex-direction:column;gap:4px;font-size:13px;color:var(--muted)}select{max-width:100%;padding:10px;border:1px solid #aebdce;border-radius:5px;background:white;color:var(--ink);font-size:15px}button{padding:10px;border:1px solid var(--line);background:white;color:var(--blue);border-radius:5px;cursor:pointer}footer{font-size:14px;color:var(--muted)}.chips{display:flex;gap:12px;flex-wrap:wrap}.chip{border:1px solid var(--line);border-radius:8px;padding:10px 14px;background:var(--paper)}@media(max-width:700px){main{padding:18px 12px 50px}section{padding:20px}.cards{grid-template-columns:1fr}.card{padding:16px}.big{font-size:29px}td,th{padding:9px}nav{font-size:14px}}
</style></head><body><main><header><div class="eyebrow">Research notebook · 29 September 2026</div><h1>Qwen3-4B<br>MOLT exploration</h1><p class="lead">From held-out reconstruction to a reproduced feature intervention—and the MOLT gates that respond to it.</p><p class="meta">Georg Lange’s MOLTs · Hanna’s transcoders · RTX 5090 · All layer and token indices are zero-based</p><nav><a href="#reconstruction">Reconstruction</a><a href="#dallas">Dallas</a><a href="#intervention">Feature intervention</a><a href="#gates">MOLT gates</a><a href="#explorer">Explore gates</a><a href="#resume">Resume</a></nav></header>
<div class="cards"><div class="card"><div class="big">58,424</div><p>Held-out tokens scored for reconstruction across 64 conversations.</p></div><div class="card"><div class="big">99.77%</div><p>P(cold) after the combined intervention on the unchanged small prompt.</p></div><div class="card"><div class="big">4→5 · 3→5</div><p>Active MOLT gates at “small,” in layers 21 and 22 respectively.</p></div></div>
<div class="note warning"><strong>Scope:</strong> these are exploratory measurements, not a validated attribution graph. Qwen MOLT Jacobian fidelity and a causal MOLT replacement for the feature intervention remain untested.</div>
<section id="reconstruction"><span class="number">01 / CHECK THE APPROXIMATION</span><h2>Released MOLTs reconstruct held-out MLP outputs</h2><p>We scored layers 17 and 25 on the same 64 UltraChat <code>test_sft</code> conversations, using native Qwen chat formatting and at most 1,024 tokens per conversation. Georg’s MOLT forward implementation and saved normalization statistics were used.</p><div class="scroll"><table><thead><tr><th>Layer</th><th>Standardized MSE</th><th>Error reduction vs saved mean</th><th>Mean active gates</th></tr></thead><tbody>RECON_ROWS</tbody></table></div><p class="meta">Error reduction is 1 − model squared error / saved-mean baseline squared error. It is not answer accuracy. The 95% conversation-bootstrap intervals were 72.21–74.70% (L17) and 79.41–81.78% (L25).</p><p>Layer 25 reconstructs better relative to its baseline on this sample. Substantial error remains in both layers. Reconstruction alone does not establish faithful responses to interventions.</p><a href="results/reconstruction-layers17-25/report.md">Detailed protocol and metrics</a></section>
<section id="dallas"><span class="number">02 / A MULTIHOP STARTING POINT</span><h2>Dallas → Texas → Austin</h2><blockquote>What is the capital of the state containing Dallas?</blockquote><div class="chips"><div class="chip">Original model: <strong>Austin.</strong></div><div class="chip">Layer 17 replaced by MOLT: <strong>Austin</strong></div></div><p>Replacement applied during prompt processing and generation, with no reconstruction-error add-back. Three additional qualitative questions retained the same numerical/geographical answers; the explanation wording varied.</p><h3>Which representations and transforms activate?</h3><p>Eight of 73 retrieved Texas-labelled transcoder candidates activated at Dallas. This was a bounded label search, not an exhaustive feature census. On the same original-model inputs, five MOLT transforms activated at Dallas in layer 17 and four in layer 25.</p>TEXAS_IMAGE<details><summary>See the Dallas MOLT gates</summary>DALLAS_IMAGE</details><p class="meta">These activations do not prove the Dallas → Texas → Austin causal path. The MOLT gates were observed without replacing the MLPs.</p><a href="results/dallas-one-word/report.md">Response comparison</a> · <a href="results/texas-features/report.md">Transcoder measurements</a> · <a href="results/dallas-molt-gates/report.md">MOLT measurements</a></section>
<section id="intervention"><span class="number">03 / REPRODUCE AN EXISTING INTERVENTION</span><h2>“Opposite of small” can be steered toward “cold”</h2><blockquote>What is the opposite of "small"? Reply with only the word, nothing else.</blockquote><p>Using the community <a href="https://github.com/wdk0082/llm-circuits/blob/af8a37ad836dc401a0ec5dbb71307d8d7ab68028/notebooks/multilingual.ipynb">llm-circuits reproduction</a>, we suppressed six small-associated transcoder directions and added six hot-associated directions. Every edit was at the <strong>small token, index 9</strong>, across layers 0, 3, 4, 5, 19, 21, and 22.</p><div class="scroll"><table><thead><tr><th>Strength</th><th>Top next token</th><th>Our P(cold)</th><th>Reference P(cold)</th></tr></thead><tbody>REPRO_ROWS</tbody></table></div>REPRO_IMAGE<div class="note"><strong>Constrained protocol:</strong> attention patterns were frozen across all layers; MLP outputs through layer 22 were pinned to original values plus the selected edits. Later MLPs recomputed normally. At strength above 1, small directions are pushed beyond zero into negative contributions.</div><p>The feature IDs and strengths were reused without a new search. The zero-delta control and restored model both matched the original logits exactly. This is a close quantitative reproduction, not a bit-identical one. It measures next-token probabilities, not unrestricted generation.</p><a href="results/small-hot-reproduction/report.md">Full reproduction and selected features</a></section>
<section id="gates"><span class="number">04 / OBSERVE THE MOLT RESPONSE</span><h2>The intervention changes which gates fire</h2><p>We captured the original and intervened inputs at layers 21 and 22, then evaluated their MOLT gate encoders separately. These MOLTs were <strong>observers</strong>; their outputs did not drive the answer. Only 52 MB of gate weights and metadata were needed.</p><div class="scroll"><table><thead><tr><th>Condition</th><th>L21 gates at operand</th><th>L22 gates at operand</th><th>Top next token</th><th>P(cold)</th></tr></thead><tbody>GATE_ROWS</tbody></table></div>GATE_IMAGE<p>For the combined edit at layer 21, <strong>#202 and #1408 turn on</strong>, while #2232 turns off. At layer 22, <strong>#40, #61, #71, and #941 turn on</strong>, while #55 and #2339 turn off.</p><p>Layer 22 gates <strong>#71 and #941</strong> also activate on the natural hot prompt, while remaining off for the original small prompt. This is a candidate correspondence, not an established hot label or proof of causal mediation.</p><p>At the final prompt position, the combined intervention preserves the active gate sets: seven gates in layer 21 and five in layer 22. Their strengths still change.</p><div class="note"><strong>Where x and x′ come from:</strong> the transcoder edits occur at MLP outputs. A layer’s MOLT input reflects earlier edits, not that layer’s own output edit. Inputs were captured before post-attention normalization, matching Georg’s checkpoint coordinates.</div><details><summary>View gate counts across every prompt token</summary>COUNTS_IMAGE</details><p class="meta">Primary gates use FP32 computation on captured BF16 residuals. The BF16-autocast sensitivity check agrees on active sets at the operand and final positions for every condition; two marginal disagreements occur elsewhere. Only gate behavior was measured here, not transform outputs or Jacobians.</p><a href="results/small-hot-molt-gates-21-22/report.md">Full gate report</a> · <a href="results/small-hot-molt-gates-21-22/counts-by-token.csv">Download counts CSV</a></section>
<section id="explorer"><span class="number">05 / INSPECT THE SAVED MEASUREMENTS</span><h2>Gate explorer</h2><p>Choose a layer, token, and condition. Values are read from the saved experiment; this page runs no model.</p><div class="controls"><label>Layer<select id="layer"><option value="21">21</option><option value="22" selected>22</option></select></label><label>Token position<select id="token"></select></label><label>Compare with original small<select id="condition"><option value="combined">Suppress + add</option><option value="suppression_only">Suppress small only</option><option value="addition_only">Add hot only</option><option value="natural_hot">Natural hot prompt</option></select></label></div><p id="gate-status" aria-live="polite"></p><div class="scroll"><table><thead><tr><th>Gate ID</th><th>Original activation</th><th>Compared activation</th><th>Change</th></tr></thead><tbody id="gate-body"></tbody></table></div><noscript>The explorer requires JavaScript; all main results above remain available without it.</noscript></section>
<section id="resume"><span class="number">06 / PRESERVE & CONTINUE</span><h2>A reproducible starting point for the next session</h2><p><strong>Archive status:</strong> STATUS_TEXT</p><p>The repository contains the code, measurements, figures, selected feature recipe, source-function hashes, and pinned model revisions. This HTML embeds its figures and explorer data for offline use. Full pretrained weights are intentionally redownloadable rather than committed.</p><p><a href="https://github.com/rakaar/qwen3-molt-exploration">Public GitHub repository</a> · <a href="README.md">Setup and rerun instructions</a> · <a href="archive-status.json">Archive status record</a></p><h3>Questions still open</h3><ul><li>Do the released Qwen MOLTs match the original MLPs’ Jacobians or finite perturbation responses?</li><li>What do the candidate layer-22 transforms compute, beyond their gate conditions?</li><li>Can editing their contributions reproduce the answer change causally?</li><li>Does a comparable intervention work without frozen attention and pinned MLP outputs?</li><li>Can this be extended to a validated multihop geography circuit?</li></ul><p class="meta">No full attribution graph or MOLT-equivalent causal swap has been demonstrated in this session.</p></section>
<footer><p>Sources: <a href="https://transformer-circuits.pub/2025/bulk-update/index.html">MOLT article</a> · <a href="https://huggingface.co/georglange/qwen3-4b-molt">Georg’s checkpoints</a> · <a href="https://github.com/Goreg12345/crosslayer-transcoder/tree/MOLT">Training code</a> · <a href="https://huggingface.co/mwhanna/qwen3-4b-transcoders">Hanna’s transcoders</a> · <a href="https://github.com/wdk0082/llm-circuits">Community reproduction</a></p><p>Research archive by Raghavendra Kaushik · 2026-09-29</p></footer></main>
<script type="application/json" id="gate-data">EXPLORER_DATA</script><script>
const data=JSON.parse(document.getElementById('gate-data').textContent);
const layer=document.getElementById('layer'),token=document.getElementById('token'),condition=document.getElementById('condition');
data.tokens.forEach(t=>{const o=document.createElement('option');o.value=t.position;o.textContent=t.position+': '+JSON.stringify(t.text);o.selected=t.position===9;token.appendChild(o)});
function render(){const l=data.layers.find(l=>l.layer===Number(layer.value)),p=Number(token.value),a=l.conditions.baseline[p],b=l.conditions[condition.value][p];const am=new Map(a.map(x=>[x.id,x.gate])),bm=new Map(b.map(x=>[x.id,x.gate]));const ids=[...new Set([...am.keys(),...bm.keys()])].sort((x,y)=>x-y);document.getElementById('gate-status').textContent=`${a.length} → ${b.length} active gates. Token ${p}${condition.value==='natural_hot'&&p===9?' is “hot” in the compared prompt.':'.'}`;const body=document.getElementById('gate-body');body.replaceChildren();ids.forEach(id=>{const x=am.get(id)||0,y=bm.get(id)||0,tr=document.createElement('tr');[id,x.toFixed(5),y.toFixed(5),(y-x>0?'+':'')+(y-x).toFixed(5)].forEach(v=>{const td=document.createElement('td');td.textContent=v;tr.appendChild(td)});body.appendChild(tr)})}
[layer,token,condition].forEach(el=>el.addEventListener('change',render));render();
</script></body></html>'''
for key,value in {'RECON_ROWS':recon_rows,'REPRO_ROWS':repro_rows,'GATE_ROWS':gate_rows,
 'TEXAS_IMAGE':image('results/texas-features/texas-on-dallas.png','Eight Texas-labelled transcoder features activate at Dallas'),
 'DALLAS_IMAGE':image('results/dallas-molt-gates/dallas-molt-gates.png','MOLT gates active at Dallas in layers 17 and 25'),
 'REPRO_IMAGE':image('results/small-hot-reproduction/comparison.png','Our next-token probabilities closely match the published reference'),
 'GATE_IMAGE':image('results/small-hot-molt-gates-21-22/operand-gates.png','MOLT gate strengths before and after intervention'),
 'COUNTS_IMAGE':image('results/small-hot-molt-gates-21-22/counts-by-token.png','Gate counts at all 29 prompt tokens'),
 'EXPLORER_DATA':json.dumps(explorer).replace('<','\\u003c'),'STATUS_TEXT':status_text}.items(): page=page.replace(key,value)
(ROOT/'index.html').write_text(page)
print('Built self-contained index.html:',len(page.encode()),'bytes')
